import { Agent, BrokerageSettings, LeadInquiry } from './types';

export const DEFAULT_BROKERAGE_SETTINGS: BrokerageSettings = {
  name: 'Vidabricks Real Estate',
  legalName: 'Vidabricks Real Estate LLC',
  reraOrn: '28472',
  phone: '+971 54 700 5470',
  email: 'info@vidabricks.com',
  website: 'https://vidabricks.com',
  address: 'Tameem House, Barsha Heights, Dubai, United Arab Emirates',
  officeLocation: 'Dubai, UAE',
  defaultWhatsappTemplate:
    'Hi {agentName}, I found your profile on Vidabricks and would like to know more about Dubai properties.',
  enablePublicDirectory: true,
  brandTagline: 'Redefining Luxury & Off-Plan Real Estate in Dubai',
  logoUrl: '/logos/vidabricks-gold.png',
  darkLogoUrl: '/logos/vidabricks-black-transparent.png',
};

export const INITIAL_AGENTS: Agent[] = [
  {
    id: 'agent-1',
    firstName: 'John',
    lastName: 'Doe',
    slug: 'john-doe',
    photo: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=800&q=85&auto=format&fit=crop',
    jobTitle: 'Senior Property Consultant',
    reraNumber: '54912',
    phone: '+971501234567',
    whatsapp: '+971501234567',
    email: 'john.doe@vidabricks.com',
    bio: 'Helping international investors and discerning homeowners make confident, high-yield property decisions across Dubai’s most prestigious communities.',
    languages: ['English', 'French', 'Arabic (Basic)'],
    nationality: 'British',
    experienceYears: 8,
    location: 'Dubai, UAE',
    specialisations: ['Off-Plan', 'Residential Sales', 'Luxury Properties', 'Investment Advisory'],
    areas: ['Palm Jumeirah', 'Downtown Dubai', 'Dubai Hills Estate', 'Arabian Ranches'],
    social: {
      linkedin: 'https://linkedin.com/in/johndoe-dubai',
      instagram: 'https://instagram.com/johndoe_realestate',
      x: 'https://x.com/johndoe_properties',
      website: 'https://agents.vidabricks.com/agents/john-doe',
    },
    focusProperties: [
      {
        id: 'prop-1',
        title: 'Palm Beach Towers Luxury Residences',
        developer: 'Nakheel',
        location: 'Palm Jumeirah',
        startingPrice: 'AED 3,850,000',
        type: '1-3 Bedroom Waterfront Suites',
        imageUrl: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80',
        tag: 'Waterfront Living',
      },
      {
        id: 'prop-2',
        title: 'Burj Crown Ultra-Penthouses',
        developer: 'Emaar Properties',
        location: 'Downtown Dubai',
        startingPrice: 'AED 6,200,000',
        type: 'Luxury Sky Mansions',
        imageUrl: 'https://images.unsplash.com/photo-1546412414-e1885259563a?w=800&q=80',
        tag: 'Burj View',
      },
    ],
    customWhatsappMessage:
      'Hi John, I found your profile on Vidabricks and would like to know more about Dubai properties.',
    status: 'active',
    isFeatured: true,
    profileViews: 3842,
    whatsappClicks: 742,
    callClicks: 218,
    emailClicks: 94,
    vcardDownloads: 341,
    shares: 185,
    inquiriesCount: 68,
    createdAt: '2025-01-15T10:00:00Z',
    updatedAt: '2026-08-25T14:30:00Z',
  },
  {
    id: 'agent-2',
    firstName: 'Sarah',
    lastName: 'Al Mansoori',
    slug: 'sarah-al-mansoori',
    photo: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=800&q=85&auto=format&fit=crop',
    jobTitle: 'Associate Director — Luxury Waterfront',
    reraNumber: '48103',
    phone: '+971547005470',
    whatsapp: '+971547005470',
    email: 'sarah.mansoori@vidabricks.com',
    bio: 'Specialising in trophy waterfront villas, branded residences, and ultra-high-net-worth acquisitions along the Arabian Gulf coastline.',
    languages: ['Arabic', 'English'],
    nationality: 'Emirati',
    experienceYears: 11,
    location: 'Dubai, UAE',
    specialisations: ['Ultra-Luxury', 'Waterfront Villas', 'Branded Residences', 'Private Off-Market'],
    areas: ['Palm Jumeirah', 'Jumeirah Bay Island', 'Bulgari Lighthouse', 'Dubai Marina'],
    social: {
      linkedin: 'https://linkedin.com/in/sarah-almansoori',
      instagram: 'https://instagram.com/sarah_dubairealestate',
      tiktok: 'https://tiktok.com/@sarah_properties',
    },
    focusProperties: [
      {
        id: 'prop-3',
        title: 'Jumeirah Bay Island Signature Villa',
        developer: 'Meraas',
        location: 'Jumeirah Bay Island',
        startingPrice: 'AED 48,000,000',
        type: '6-Bedroom Bespoke Beachfront Mansion',
        imageUrl: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80',
        tag: 'Ultra-Exclusive',
      },
    ],
    customWhatsappMessage:
      'Hello Sarah, I would like to discuss exclusive luxury waterfront properties in Dubai.',
    status: 'active',
    isFeatured: true,
    profileViews: 4210,
    whatsappClicks: 890,
    callClicks: 340,
    emailClicks: 120,
    vcardDownloads: 410,
    shares: 220,
    inquiriesCount: 84,
    createdAt: '2025-02-01T12:00:00Z',
    updatedAt: '2026-08-27T09:15:00Z',
  },
  {
    id: 'agent-3',
    firstName: 'Mikhail',
    lastName: 'Romanov',
    slug: 'mikhail-romanov',
    photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&q=85&auto=format&fit=crop',
    jobTitle: 'Head of Off-Plan Investments',
    reraNumber: '61924',
    phone: '+971559876543',
    whatsapp: '+971559876543',
    email: 'mikhail.romanov@vidabricks.com',
    bio: 'Maximising investor ROI through early-access off-plan launch allocations, capital appreciation strategies, and turnkey portfolio structuring.',
    languages: ['Russian', 'English'],
    nationality: 'Russian',
    experienceYears: 7,
    location: 'Dubai, UAE',
    specialisations: ['Off-Plan Launches', 'Portfolio Management', 'High ROI Yields', 'Golden Visa Advisory'],
    areas: ['Business Bay', 'Dubai Hills', 'Dubai Creek Harbour', 'Emaar Beachfront'],
    social: {
      linkedin: 'https://linkedin.com/in/mikhail-romanov-dxb',
      instagram: 'https://instagram.com/mikhail_invest_dubai',
      youtube: 'https://youtube.com/@mikhail_dubairealestate',
    },
    focusProperties: [
      {
        id: 'prop-4',
        title: 'Creek Waters Premier Collection',
        developer: 'Emaar Properties',
        location: 'Dubai Creek Harbour',
        startingPrice: 'AED 2,200,000',
        type: '1-4 Bedroom Waterfront Towers',
        imageUrl: 'https://images.unsplash.com/photo-1582407947304-fd86f028f716?w=800&q=80',
        tag: 'High Yield ROI',
      },
    ],
    customWhatsappMessage:
      'Hi Mikhail, I am interested in new off-plan launches and investment opportunities with Vidabricks.',
    status: 'active',
    isFeatured: true,
    profileViews: 2950,
    whatsappClicks: 520,
    callClicks: 165,
    emailClicks: 72,
    vcardDownloads: 230,
    shares: 110,
    inquiriesCount: 49,
    createdAt: '2025-03-10T14:20:00Z',
    updatedAt: '2026-08-20T16:45:00Z',
  },
  {
    id: 'agent-4',
    firstName: 'Elena',
    lastName: 'Vance',
    slug: 'elena-vance',
    photo: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=800&q=85&auto=format&fit=crop',
    jobTitle: 'Private Client Advisor',
    reraNumber: '59381',
    phone: '+971523344556',
    whatsapp: '+971523344556',
    email: 'elena.vance@vidabricks.com',
    bio: 'Dedicated to connecting international families and European investors with prime residential master-communities and resort-style lifestyle homes in Dubai.',
    languages: ['English', 'German', 'Spanish'],
    nationality: 'German',
    experienceYears: 6,
    location: 'Dubai, UAE',
    specialisations: ['Family Communities', 'Golf Estates', 'Resort Villas', 'Secondary Market'],
    areas: ['Tilal Al Ghaf', 'Dubai Hills Estate', 'Jumeirah Golf Estates', 'Sobha Hartland'],
    social: {
      linkedin: 'https://linkedin.com/in/elena-vance-realestate',
      instagram: 'https://instagram.com/elena_luxury_dubai',
    },
    focusProperties: [
      {
        id: 'prop-5',
        title: 'Lanai Islands Crystal Lagoon Mansions',
        developer: 'Majid Al Futtaim',
        location: 'Tilal Al Ghaf',
        startingPrice: 'AED 32,000,000',
        type: '7-Bedroom Private Island Estate',
        imageUrl: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&q=80',
        tag: 'Lagoon Estate',
      },
    ],
    customWhatsappMessage:
      'Hi Elena, I would like to explore luxury family residences and villas in Dubai.',
    status: 'active',
    isFeatured: false,
    profileViews: 1840,
    whatsappClicks: 310,
    callClicks: 95,
    emailClicks: 40,
    vcardDownloads: 160,
    shares: 88,
    inquiriesCount: 29,
    createdAt: '2025-04-18T11:10:00Z',
    updatedAt: '2026-08-24T18:00:00Z',
  },
  {
    id: 'agent-5',
    firstName: 'Rashid',
    lastName: 'Khan',
    slug: 'rashid-khan',
    photo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=800&q=85&auto=format&fit=crop',
    jobTitle: 'Commercial & Prime Real Estate Specialist',
    reraNumber: '42817',
    phone: '+971567890123',
    whatsapp: '+971567890123',
    email: 'rashid.khan@vidabricks.com',
    bio: 'Strategic commercial property advisor catering to family offices, institutional capital, and corporate headquarter acquisitions in Dubai’s premier business hubs.',
    languages: ['English', 'Hindi', 'Urdu', 'Arabic (Conversational)'],
    nationality: 'Pakistani',
    experienceYears: 14,
    location: 'Dubai, UAE',
    specialisations: ['Commercial Real Estate', 'DIFC Offices', 'Retail Assets', 'Full Buildings'],
    areas: ['DIFC', 'Downtown Dubai', 'Business Bay', 'Sheikh Zayed Road'],
    social: {
      linkedin: 'https://linkedin.com/in/rashid-khan-commercial',
      x: 'https://x.com/rashid_commercial_dxb',
    },
    focusProperties: [
      {
        id: 'prop-6',
        title: 'DIFC Gate Avenue Grade-A Commercial Tower',
        developer: 'DIFC Properties',
        location: 'DIFC',
        startingPrice: 'AED 18,500,000',
        type: 'Prime Grade-A Office Floor',
        imageUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&q=80',
        tag: 'DIFC Financial Hub',
      },
    ],
    customWhatsappMessage:
      'Hello Rashid, I would like to consult on commercial property opportunities in Dubai.',
    status: 'inactive',
    isFeatured: false,
    profileViews: 1250,
    whatsappClicks: 180,
    callClicks: 65,
    emailClicks: 32,
    vcardDownloads: 95,
    shares: 42,
    inquiriesCount: 16,
    createdAt: '2025-05-05T09:00:00Z',
    updatedAt: '2026-08-28T10:00:00Z',
  },
];

export const INITIAL_LEADS: LeadInquiry[] = [
  {
    id: 'lead-1',
    agentId: 'agent-1',
    agentName: 'John Doe',
    clientName: 'Alexander Hayes',
    clientPhone: '+44 7700 900077',
    clientEmail: 'a.hayes@investorcapital.uk',
    propertyInterest: 'Palm Beach Towers Luxury Residences',
    budgetRange: 'AED 4M – 8M',
    message: 'Looking for a 2-bedroom sea-view off-plan unit with post-handover payment plan.',
    createdAt: '2026-08-28T14:10:00Z',
    status: 'new',
  },
  {
    id: 'lead-2',
    agentId: 'agent-2',
    agentName: 'Sarah Al Mansoori',
    clientName: 'Dr. Tariq Al Nuaimi',
    clientPhone: '+971 50 882 1994',
    clientEmail: 'tariq.nuaimi@medgroup.ae',
    propertyInterest: 'Jumeirah Bay Island Signature Villa',
    budgetRange: 'AED 40M+',
    message: 'Seeking a private beachfront plot or modern signature mansion.',
    createdAt: '2026-08-27T19:45:00Z',
    status: 'contacted',
  },
  {
    id: 'lead-3',
    agentId: 'agent-3',
    agentName: 'Mikhail Romanov',
    clientName: 'Dmitry Sokolov',
    clientPhone: '+971 52 441 9832',
    clientEmail: 'sokolov.d@nordventures.ch',
    propertyInterest: 'Creek Waters Collection',
    budgetRange: 'AED 2M – 5M',
    message: 'Interested in buying 3 units for rental yield and Golden Visa qualification.',
    createdAt: '2026-08-26T11:20:00Z',
    status: 'contacted',
  },
];
